<a href="https://colab.research.google.com/github/BenCoder302/Google-Colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Basics

In [5]:
import numpy as np
print(np.__version__)

1.23.5


In [6]:
a = np.array([1, 2, 3]) # 1-D array
print(a)
print(a.shape) # Returns a tuple
print(a.dtype) # Returns data type
print(a.ndim) # Returns dimensions of array
print(a.size) # Returns no. of elements
print(a.itemsize) # Returns sie of each element

[1 2 3]
(3,)
int64
1
3
8


In [7]:
print(a[0]) # Accessing elements
a[0] = 10 # Modifing elements
print(a)

1
[10  2  3]


In [8]:
b = a * np.array([2, 0, 2])
print(b)

[20  0  6]


## Lists vs np_arrays
Opertions in numpy arrays wrok element-wise

# Addition

In [9]:
l = [1, 2, 3]
l = l +  [4]
print(l)

a = np.array([1, 2, 3])
a = a + np.array([4]) # Equivalent to a = a + np.array([4, 4, 4])
print(a)

[1, 2, 3, 4]
[5 6 7]


# Multiplication

In [10]:
l = [1, 2, 3]
l = l * 2
print(l)

a = np.array([1, 2, 3])
a = a * 2
print(a)

[1, 2, 3, 1, 2, 3]
[2 4 6]
